<?php

namespace App\Console\Commands;

use App\Model\Master\Customer;
use App\Model\Master\Group;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class PriorityCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'dev:priority';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Priority';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $this->line('Surabaya');
        $prs = 'UMAYAH;EKA JAYA;VIDO GARMENT KERTAJAYA;TOKO ANEKA;QUEST HOTEL;DIES NATALIS;TOKO ANUGRAH;WR KANG UCUP;DEPOT HJ. LAUIGI;TOKO ASIA;WK WAHYU;TOKO MUMTAZ;TOKO SINAR TERANG;WR MAMIRAH;WK BIRU;WK 1927;TOKO RAPI JAYA;WK KUNING;TOKO MAJU JAYA;TOKO NABILA;WK BIRU;KEDAI KOPI IJO;TOKO RAHAYU;TOKO ADI;WK KUNING;GIRAS PALAPA;TK HJ. BAROKAH;TOKO SUMBER REJEKI;TOKO ISHA;TOKO AL KAHFI;WK DIKA;WR BU SANY;WK LANCAR;WM SOPOYONO;WK PAK SU;WK 81;MINI MARKET KEVIN;APOTEK SMILEPLUS;TOKO HDR;HOTEL AMARIS;WR CAK PEQ;TK MUNAWAROH;WK CAK SAN;WK RASA BEDA;WK 37;TOKO KURNIA;WK DULUR DEWE;WR MBAK INDAH;WK ALAMI KALIJUDAN;TOKO MIKRO;TOKO GHOZI;WK 75;WK IJO;TOKO MANYAR;WK 81;ANGKRINGAN JOGJA;WK BAROKAH;WK 57;WK HERU;NAURA COFFEE;TOKO CICI;TOKO ATIKA;KEDAI 71;TOKO KAYASAH;WK BAIM;WK 67;D\'SAL CAFÉ;GIRAS 51;WK 73;WK WBL;WK FAUZI;WR CAK AN;TOKO SURYA;TOKO QUBA;TOKO LICHA JAYA;TOKO BAROKAH;TOKO MAKMUR;BU SARI;WM 38;WR WAHYUNI;WK RICKBOYO;WR BU SRI;TOKO SEJAHTERA;TOKO MAYA;WK WILIS;WR ISTIQOMAH;WR ASTY;WR BU SUSI';
        $this->prior('point_kbsurabaya', $prs);

        $this->line('Probolinggo');
        $prs = 'WR B UMI;WR FIF;WR LESEHAN 676;WR UMK;WR BU DEA;WR BU UMI;WR BU IMA;WR BU MURATIH;WR BU TUTIK';
        $this->prior('point_kbprobolinggo', $prs);

        $this->line('Mojokerto');
        $prs = 'WK JACOST;WK POJOK TOWER;WK SIANIDA;WK NUTRISI;WK BU SUWITO;WARUNG IJO KUTOREJO;TK BAROKAH;AGEN TIGA PUTRA;SAMBEL WADER;WM BU FARIDA;WK PBI;JACOST COFFEE;OMAH KOPI;WK MBAK LILIK;LESEHAN CANTIKA;TSAMANIA PLOSO MM;JACOST COFFEE;RISKA MART;EKA LESTARI MM;TSAMANIA PLOSO MM;BINTANG MART;MOJO MART;ORANGE MART;ALIFAH MART;KARTINI MM;BUSINESS CENTRE;WK BU TUM;WK SAIDI;WK VELLY;WK GOTONG ROYONG;MBAH MAN;WK TAMAN;WK ALFA;WK AFFI;SENTRA COFFEE;WK BU SANI;WK CAK RENGES;WK CAK MIN;WK SEDERHANA;MBAK SISWATI;WR RIRIN;DUA PUTRI;PAK HERU;PACETOZ;WK MBAK NAH;WK TAHTA;WK RIRIS;WK 76;MARDIAH;WK JOKO TOLE;MIE CEKER;MBAH MAN;SEDERHANA;MBAK DWI;WK NB;JUKIYAH;KOPI GIRAS;FA2 KOPI;WK 2000;WK COC;WK RT;WK BAROKAH;WK IJO;WK JAMAL;WK CAHAYA;WKBUMI GOJEK;WK ANGGUN;WK RAHMAT;WK PAK MAN;WK PERTIGAAN;KEDAI SEGARAN;SAMBAL BOTOK;WK GEMBIRA;POST KULINER;MAS ANGGA;BU SARNI;BU TITIN;MAS ANGGA;WK PAK RAHMAT ROLAK;WR PAK MAN;GOJEK BU UMI;WK AGUS;PAK WAN;WR PAK SHOLEH;WR LARIS;WR BU SULIATI;WK ANDA;WR LARIS;WR PAK TARYO;WR PAK NARDI;UD RUKUN';
        $this->prior('point_kbmojokerto', $prs);

        $this->line('Malang');
        $prs = 'WARUNG NINIK;WARUNG PURWATI;WARUNG RENGGANI;WARUNG TOMY;WARUNG CAK BOTOL;WARUNG NANO;WARUNG HJ. HENY ;WARUNG JAMU JAGO;WARUNG SOL;WARUNG BUNI;WARUNG STMJ;WARUNG MAHAKAM;WARUNG HANNY;WARUNG RENGGANI;TOKO CAK DIR;WARUNG MISURIP;WARUNG ASNANIK;TOKO KENARI;WARUNG SEDERHANA;WARUNG BANI;WARUNG AE;WARUNG AE;DJIBRIEL';
        $this->prior('point_kbmalang', $prs);

        $this->line('Sidoarjo');
        $prs = 'RIZKY SNACK;KOPERASI MUTIARA BUNDA;TOKO BELLA;WARKOP BU GITA;WARKOP MAS EDI;KEDAI KOPI ;WARUNG RIDHO JAYA;TOKO SAHABAT GERABAH;WARKOP GRESIK;WARKOP TRISTAR;WARKOP PUSER;KEDAI KOPI MAREM;TOKO JAHIT BU WIWIK;WARKOP MAYA CELL;TOKO FAIZ JAYA;WARKOP KALIDAWIR;WARUNG BANG UDIN;WARUNG MORO KANGEN;WARKOP STUBE;WARUNG MBAK ANIS;WARKOP MAKSUS;WARKOP CAK SAN;WARKOP KARTIKA;WARKOP MAULANA;TOKO PERMAI;TOKO ROHMAH;TOKO GEMBIRA;WARKOP BU DEWI;WARKOP BARITO;WK WARMINDO;TK PERACANGAN;WK 212;WR WAROHMAN;WK ISMAIL;WK WILUDAN;WK CANDI PARI;TK DUA PUTRA;TK JAYA ABADI;WK MBAK DINA;WR POJOK;TOKO SGM;TOKO SUMACH;TOKO NONO;TOKO PEPELEGI;WK MAJU LANCAR;WK MAYACELL;WK CILOK;WK BANG OCHING;WK BONEK;WK RAHAYU;WK GIRAS;WK AMBONA;WK ANDA;WR NRIMO;BROW WK;WK PMC;WK BBM;WK CAK TAKIM;WK MBAK ITA;WK POJOK;WK MAESTRO;GIRAS UP;WR BIRU;WK DAKOTA;WK MOKO;WR PAK JALI;WK NGOPI;WK 88;WK K74;TOKO BU ANI;WK KUNING;WK SAHABAT;WK KS;WK BRAMA;WK PODO NGOWOS;TOKO BAHARI;WK CAK GENDUT;WK BAROKAH;WK BIMA;CAFÉ SONGO;WR KEMANGI;WE KOPI;WK LESEHAN;WK MBAK IMA;WK UCUP;WK SEDATI GEDHE;WK TASYA;TOKO MULYA;WK BUMIJOYO;TOKO BELA;WK 96;WK HIJAU;WR CAK ADI;WK BUNGA;WK BOLA;WK DARMA;TOKO MEKARSARI;WR PAK DE;WK KING;WK IJO PODOMORO;WK LEK CHEN;WK POJOK PERUM;WK DIKMA;WR BU ANIE;WK AREK BONEK;WK BAROKAH BRO;WK WAGE;WR ERNI;WK MAS NANG;WR JRENG;WARNAS BU YUN;WR LAMONGAN;TOKO DAHLIA;WK FAJAR;WK SEPEDA;WK PERSEBAYA;WR CAK SOTO;WK JAVA;WK TEBEL;WK CAK MAIL;WK CAK UNYIL;WK SARI PADANG;WR BU NURUL;OMBE COFFEE;WK SINYONIA;WK ICHA;WK PENDOWO;TOKO TELATEN;WK DELIMA;TOKO RIZ;WK KHAYANGAN;WR BUT;WK MASTER COFFEE;WK LIMO;WK ARBERO;WK RATIH;WK TOP;WR BU ZAENAL;WK POS;WK BEJO;WK BU SITI';
        $this->prior('point_kbsidoarjo', $prs);

        $this->line('Bojonegoro');
        $prs = 'TOKO BAROKAH;WARKOP YANO LAMA;TOKO TYA;TOKO SANJAYA ;TOKO BU MUFIDA;TOKO MANFAAT;TOKO KUSUMA;TOKO HJ RAMLAH;WARKOP WEDANG KOPI;WARKOP TELON;WARKOP BU MASTIAH;WARKOP BU MASTIAH;WARUNG NGESONG;WARUNG LEK HAN;WARUNG PAK YUDA;WARKOP PRD;WARKOP PAK KARTO;TOKO SEMI;WARKOP MBAK LUK;WARKOP PAK YAS;WARKOP INDI;WARKOP TELON;WARKOP JITU;WARKOP HESTY;CAFE MANIA;WARKOP DEVI;WARKOP P. LILIK;WARKOP G COFE;WARKOP NDOPLOK;WARKOP WIFI;WARKOP GOYENG;TOKO DIAN;WARKOP HIMALAYA;WARKOP DIAN;TOKO NIA PUTRI;TOKO LIZA;WARKOP PAK BEN;TOKO AR-ROHMAD;WARKOP WASIAT;WARKOP MBAH UTI;WARKOP 77;WARKOP JEMBLEM;WARKOP MAS ANTOK;CAFE TAMAN;CAFE DENI;WARING LECO;CAFE DJ;WARUNG ABAH;WARKOP WR PAK ALI;WARUNG PAK MAN;WARUNG PAK ALI;CAFE 99;WARKOP MARKAS;WARKOP MAHKOTA;WARUNG MBAH SULI;WARKOP MINA;WARKOP KARTIKA;WARKOP P. DECIMIK;WARKOP BU PATI;WARKOP TEBE;WARKOP WAGU;WARKOP 02;WARKOP PJP;WARKOP PHP;TOKO FEBRIAN;TOKO BIRU';
        $this->prior('point_kbbojonegoro', $prs);

        $this->line('Banyuwangi');
        $prs = 'TOKO BOBOCI;PELITA;WR MBAK SOL;WR YANSEN;WR SILIR - SILIR;TOKO DAMAI 614;CON CON MART;TOKO PAK ANDRE;AL - MARKET;KEDAI KOPI BASMALAH;TOKO SRI REJEKI;TOKO JAGO';
        $this->prior('point_kbbanyuwangi', $prs);

        $this->line('Situbondowoso');
        $prs = 'TOKO BAHRUL;SUMBER REJEKI;ULTRA CAFE;ROBBY;MAGENDA;TK OPIK;WR ADI;AUTO;WR CAK NYO;WR SITI SAODAH;MARDIYAH;WR POKOK;LANCAR INDAH;WK HERI;TOKO HARAPAN';
        $this->prior('point_kbsitubondowoso', $prs);
    }

    public function prior($table, $prs)
    {
        config()->set('database.connections.tenant.database', $table);
        DB::connection('tenant')->reconnect();
        DB::connection('tenant')->beginTransaction();

        $group = Group::first();

        if (!$group) {
            $this->line($table . ' has no group ');
            $group = new Group;
            $group->name = 'priority';
            $group->type = 'Customer';
            $group->save();
        } else if ($group->name == 'priority') {
            $group->type = 'Customer';
            $group->save();
        }

        $customers = explode(';', $prs);
        $array = [];
        foreach ($customers as $customerName) {
            $customer = Customer::where('name', $customerName)->first();
            if ($customer) {
                if ($customer->groups) {
                    array_push($array, $customer->id);
                }
            }
        }
        if (count($array)) {
            $group->customers()->sync($array);
        }

        DB::connection('tenant')->commit();
    }
}
